{% set version = "19.0.2" %}

package:
  name: pyzmq
  version: {{ version }}

source:
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: 296540a065c8c21b26d63e3cea2d1d57902373b16e4256afe46422691903a438

build:
  number: 2

# On Windows pyzmq includes tweetnacl so libsodium is not used.
# We should revisit these in the future. However, packaging libsodium
# on Windows is complicated by the fact that they ship project files,
# but don't include one for VS 2008, which we would need for Python 2.7.
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - zeromq
    - libsodium
    - py  # [python_impl == 'pypy']
  run:
    - python
    - zeromq
    - libsodium
    - py  # [python_impl == 'pypy']

test:
  imports:
    - zmq
    - zmq.backend.cython.socket  # [python_impl == 'cpython']
    - zmq.backend.cython.utils   # [python_impl == 'cpython']
    - zmq.backend.cffi           # [python_impl == 'pypy']
    - zmq.devices.monitoredqueue

  requires:
    - pytest

  # We run the zmq tests on all platforms except Windows.
  # The only reason not to run the tests on Windows is that
  # they terminate with an interactive prompt. See also
  # https://github.com/conda-forge/staged-recipes/pull/292#issuecomment-208080893.
  # TestSocket.test_large_send is skipped on upstream CI for pypy
  commands:   # [not win]
    - py.test --pyargs zmq.tests.test_socket  # [not win and python_impl == 'cpython']
    - py.test  -k 'not test_large_send' --pyargs zmq.tests.test_socket  # [not win and python_impl == 'pypy']

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD-3-clause
  license_file: COPYING.BSD

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
