{% set version = "15.3.0" %}
package:
  name: pyzmq
  version: {{ version }}

source:
  fn: pyzmq-{{ version }}.tar.gz
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: c4b387071ece45c451c9badf51e02e0a5513fe89abf11dffdf95e81e394d5cf4

build:
  number: 0

# On Windows ZeroMQ is bundled with pyzmq.
# On Windows pyzmq includes tweetnacl so libsodium is not used.
# We should revisit these in the future. However, packaging libsodium
# on Windows is complicated by the fact that they ship project files,
# but don't include one for VS 2008, which we would need for Python 2.7.
requirements:
  build:
    - pkg-config  # [not win]
    - python
    - zeromq      # [not win]
    - libsodium   # [not win]
  run:
    - python
    - zeromq      # [not win]
    - libsodium   # [not win]

test:
  imports:
    - zmq
    - zmq.backend.cython.socket
    - zmq.backend.cython.utils
    - zmq.devices.monitoredqueue

  requires:
    - pytest

  # We run the zmq tests on all platforms except Windows.
  # The only reason not to run the tests on Windows is that
  # they terminate with an interactive prompt. See also
  # https://github.com/conda-forge/staged-recipes/pull/292#issuecomment-208080893.
  commands:                # [not win]
    - py.test --pyargs zmq.tests  # [not win]

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
