{% set version = "16.0.2" %}
package:
  name: pyzmq
  version: {{ version }}

source:
  fn: pyzmq-{{ version }}.tar.gz
  # We use the pypi URL as it includes the prepared Cython files.
  url: https://pypi.io/packages/source/p/pyzmq/pyzmq-{{ version }}.tar.gz
  sha256: 0322543fff5ab6f87d11a8a099c4c07dd8a1719040084b6ce9162bcdf5c45c9d

build:
  number: 2

requirements:
  build:
    - pkg-config   # [not win]
    - python
    - zeromq 4.2*
    - libsodium    # [not (win and py27)]
  run:
    - python
    - zeromq 4.2*
    - libsodium    # [not (win and py27)]

test:
  imports:
    - zmq
    - zmq.backend.cython.socket
    - zmq.backend.cython.utils
    - zmq.devices.monitoredqueue

  requires:
    - pytest

  # We run the zmq tests on all platforms except Windows.
  # The only reason not to run the tests on Windows is that
  # they terminate with an interactive prompt. See also
  # https://github.com/conda-forge/staged-recipes/pull/292#issuecomment-208080893.
  commands:                # [not win]
    - py.test --pyargs zmq.tests.test_socket  # [not win]

about:
  home: https://github.com/zeromq/pyzmq
  summary: Python bindings for zeromq
  license: BSD 3-clause

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - msarahan
    - pelson
