schema_version: 1

context:
  version: 27.1.0
  # build abi3 on Python 3.12
  # skip abi3-compatible Pythons later than that
  abi3_python: "3.12"
  skip_abi3_python: ">=3.13"
  build_abi3: ${{ match(python, abi3_python + ".*") and is_abi3 }}
  skip_build: ${{ match(python, skip_abi3_python) and is_abi3 }}
  abi3_tag: ${{ "cp312" if build_abi3 else "" }}

package:
  name: pyzmq
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/p/pyzmq/pyzmq-${{ version }}.tar.gz
  sha256: ac0765e3d44455adb6ddbf4417dcce460fc40a05978c08efdf2948072f6db540

build:
  number: 0
  script:
    content:
      - ${{ PYTHON }} -m pip install -v .
    env:
      # make sure it doesn't fallback on bundled libzmq
      PYZMQ_NO_BUNDLE: "1"
      SKBUILD_BUILD_VERBOSE: "true"
      SKBUILD_WHEEL_PY_API: ${{ abi3_tag }}
  skip: skip_build
  python:
    version_independent: ${{ build_abi3 }}

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - if: python_impl == 'cpython'
          then:
            - cython >=3.1
          else:
            - cffi

    - if: not win
      then:
        - pkg-config
        - make
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    # cmake 4.1 breaks cross-compilation
    - cmake 4.0.*
  host:
    - python
    - pip
    - if: python_impl == 'cpython'
      then:
        - cython >=3.1
      else:
        - cffi
    - scikit-build-core
    - zeromq
    - if: build_abi3
      then:
        - python-abi3
  run:
    - python

tests:
  - python:
      pip_check: true
      imports:
        - zmq
        - if: python_impl == 'cpython'
          then:
            - zmq.backend.cython
          else:
            - zmq.backend.cffi

  - files:
      recipe:
        - tests/
    requirements:
      run:
        - pytest
    script:
      - pytest -v tests/

  # additional tests for abi3 builds
  - if: build_abi3 and not win
    then:
      - script:
          # specify Python version because rattler.build doesn't set $SP_DIR
          # (or any standard variables it should)
          # in the test env
          - abi3audit  $PREFIX/lib/python3.12/site-packages/zmq/backend/cython/_zmq*.so -s -v --assume-minimum-abi3 ${{ abi3_python }}
        requirements:
          run:
            - python 3.12.*
            - abi3audit

      # run tests for more than one abi3 Python
      # to make sure it really works
      - files:
          recipe:
            - tests/
        requirements:
          run:
            - pytest
            - python 3.13.*
        script:
          - pytest -v tests/
      - files:
          recipe:
            - tests/
        requirements:
          run:
            - pytest
            - python 3.14.*
        script:
          - pytest -v tests/


about:
  summary: Python bindings for zeromq
  license: BSD-3-Clause
  license_file:
    - LICENSE.md
  homepage: https://github.com/zeromq/pyzmq

extra:
  recipe-maintainers:
    - jan-janssen
    - jakirkham
    - minrk
    - msarahan
    - pelson
    - SylvainCorlay
    - JohanMabille
    - ocefpaf
